name: MakeCode Build
on:
  push:
    paths-ignore:
      - "botsim/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - run: npm install -g makecode
      - run: sh mkhex.sh
